In [253]:
import sklearn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
from datetime import datetime

In [254]:
%matplotlib inline

In [274]:
def read_data(train_data_path, test_data_path):
    train = pd.read_csv(train_data_path)
    test = pd.read_csv(test_data_path)
    return train,test

In [275]:
def transform_data(data):
    data["casual"] = 0
    data["registered"] = 0
    
    parser = lambda x: datetime.strptime(x, "%Y-%m-%d %H:%M:%S")
    
    dates = pd.DataFrame({"datetime" : parser(value) for value in data["datetime"]})
    dates["year"]= [date.year for date in dates[0]]
    dates["month"]= [date.month for date in dates[0]]
    dates["day"]= [date.day for date in dates[0]]
    dates = dates.drop("datetime", axis=1)
    data = data.drop(labels=["datetime", "casual", "registered"], axis=1)
    return pd.concat([data, dates], axis=1)

def splitXy(data, target):
    y = data[target]

In [257]:
train_transformed = transform_data(train)
test_transformed = transform_data(test)

In [270]:
X = train_transformed.drop("count", axis=1)
y = train_transformed["count"]

# data_to_encode = pd.concat([train_transformed["season"], test_transformed["season"]

from sklearn.preprocessing import OneHotEncoder
# encoder = OneHotEncoder()
# encoder.fit(all_data)

# X = encoder.transform(X)
# X_real = encoder.transform(test_transformed)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)
X_test

,year,month,day,season,holiday,workingday,weather,temp,atemp,humidity,windspeed
6495,2012,3,7,1,0,1,1,18.04,21.970,62,16.9979
7050,2012,4,12,2,0,1,1,13.12,15.150,61,16.9979
558,2011,2,6,1,0,0,1,12.30,14.395,52,16.9979
5085,2011,12,5,4,0,1,2,18.86,22.725,88,8.9981
3328,2011,8,8,3,0,1,1,33.62,37.120,43,19.9995
1368,2011,4,2,2,0,0,1,13.12,15.150,61,16.9979
3453,2011,8,13,3,0,0,2,27.88,31.820,79,19.0012
1535,2011,4,9,2,0,0,2,15.58,19.695,87,11.0014
449,2011,2,1,1,0,1,2,9.84,12.120,81,8.9981
7626,2012,5,17,2,0,1,1,24.60,29.545,73,16.9979
97,2011,1,5,1,0,1,1,8.20,9.850,47,15.0013
2259,2011,6,2,2,0,1,1,29.52,32.575,38,7.0015
7923,2012,6,10,2,0,0,1,33.62,35.605,30,0.0000
661,2011,2,10,1,0,1,1,5.74,8.335,28,7.0015
5777,2012,1,15,1,0,0,1,6.56,8.335,40,11.0014
9616,2012,10,5,4,0,1,1,22.14,25.760,68,7.0015
7618,2012,5,16,2,0,1,1,28.70,32.575,54,19.0012
2922,2011,7,10,3,0,0,1,34.44,37.880,41,19.0012
2713,2011,7,1,3,0,1,1,27.88,31.820,47,6.0032
658,2011,2,10,1,0,1,1,8.20,9.090,27,19.9995
2524,2011,6,13,2,0,1,1,25.42,29.545,73,19.0012
2739,2011,7,3,3,0,0,2,28.70,32.575,61,11.0014
8509,2012,7,15,3,0,0,1,29.52,34.850,74,7.0015
4153,2011,10,5,4,0,1,1,18.86,22.725,82,11.0014
4147,2011,10,4,4,0,1,1,21.32,25.000,68,15.0013
2738,2011,7,3,3,0,0,1,28.70,32.575,58,15.0013
2980,2011,7,13,3,0,1,1,31.16,34.850,55,0.0000
9527,2012,10,1,4,0,1,2,18.86,22.725,77,7.0015
10772,2012,12,15,4,0,0,2,9.84,14.395,75,0.0000
2670,2011,6,19,2,0,0,2,27.06,31.060,74,8.9981
...,...,...,...,...,...,...,...,...,...,...,...
3745,2011,9,7,3,0,1,2,22.14,25.760,94,15.0013
9792,2012,10,12,4,0,1,1,20.50,24.240,39,19.9995
3648,2011,9,2,3,0,1,2,26.24,30.305,73,11.0014
3468,2011,8,14,3,0,0,1,28.70,33.335,79,15.0013
7123,2012,4,15,2,0,0,2,22.14,25.760,52,0.0000
2260,2011,6,2,2,0,1,1,28.70,31.820,39,0.0000
3945,2011,9,15,3,0,1,2,27.06,31.060,69,16.9979
880,2011,3,1,1,0,1,1,9.02,10.605,69,19.0012
10775,2012,12,15,4,0,0,1,10.66,13.635,75,7.0015
4844,2011,11,14,4,0,1,1,23.78,27.275,56,23.9994
4137,2011,10,4,4,0,1,1,19.68,23.485,67,19.0012
1798,2011,5,1,2,0,0,2,18.86,22.725,82,0.0000
2014,2011,5,10,2,0,1,1,22.14,25.760,60,8.9981
9330,2012,9,12,3,0,1,1,20.50,24.240,77,6.0032
7652,2012,5,18,2,0,1,1,18.86,22.725,77,7.0015
243,2011,1,11,1,0,1,2,8.20,11.365,51,7.0015
2487,2011,6,11,2,0,0,1,32.80,37.880,55,12.9980
3658,2011,9,3,3,0,0,1,26.24,30.305,69,11.0014
7542,2012,5,13,2,0,0,1,29.52,32.575,45,23.9994
6490,2012,3,7,1,0,1,1,22.96,26.515,37,27.9993
486,2011,2,3,1,0,1,1,6.56,6.820,47,19.9995
6083,2012,2,9,1,0,1,1,13.94,16.665,34,8.9981
10756,2012,12,14,4,0,1,1,16.40,20.455,43,12.9980
8931,2012,8,14,3,0,1,1,31.98,35.605,49,8.9981
7402,2012,5,7,2,0,1,1,23.78,27.275,56,22.0028
5938,2012,2,3,1,0,1,1,15.58,19.695,40,0.0000
869,2011,2,19,1,0,0,1,18.04,21.970,16,43.0006
6698,2012,3,16,1,0,1,2,17.22,21.210,82,0.0000
2157,2011,5,16,2,0,1,1,23.78,27.275,83,16.9979
4179,2011,10,6,4,0,1,1,18.04,21.970,62,19.0012

In [271]:
from sklearn import tree
clf = tree.DecisionTreeRegressor()
clf = clf.fit(X_train, y_train)

In [272]:
clf.score(X_test, y_test)

-0.026932104391383715

In [232]:
test_transformed = transform_data(test)

In [273]:
clf.predict(X_real)

ValueError: Number of features of the model must match the input. Model n_features is 11 and input n_features is 266

In [ ]:
dd

In [119]:
train_transformed

,atemp,casual,count,holiday,humidity,registered,season,temp,weather,windspeed,workingday,0,year,month,day
0,14.395,3.0,16.0,0.0,81.0,13.0,1.0,9.84,1.0,0.0000,0.0,NaT,NaN,NaN,NaN
1,13.635,8.0,40.0,0.0,80.0,32.0,1.0,9.02,1.0,0.0000,0.0,NaT,NaN,NaN,NaN
2,13.635,5.0,32.0,0.0,80.0,27.0,1.0,9.02,1.0,0.0000,0.0,NaT,NaN,NaN,NaN
3,14.395,3.0,13.0,0.0,75.0,10.0,1.0,9.84,1.0,0.0000,0.0,NaT,NaN,NaN,NaN
4,14.395,0.0,1.0,0.0,75.0,1.0,1.0,9.84,1.0,0.0000,0.0,NaT,NaN,NaN,NaN
5,12.880,0.0,1.0,0.0,75.0,1.0,1.0,9.84,2.0,6.0032,0.0,NaT,NaN,NaN,NaN
6,13.635,2.0,2.0,0.0,80.0,0.0,1.0,9.02,1.0,0.0000,0.0,NaT,NaN,NaN,NaN
7,12.880,1.0,3.0,0.0,86.0,2.0,1.0,8.20,1.0,0.0000,0.0,NaT,NaN,NaN,NaN
8,14.395,1.0,8.0,0.0,75.0,7.0,1.0,9.84,1.0,0.0000,0.0,NaT,NaN,NaN,NaN
9,17.425,8.0,14.0,0.0,76.0,6.0,1.0,13.12,1.0,0.0000,0.0,NaT,NaN,NaN,NaN
10,19.695,12.0,36.0,0.0,76.0,24.0,1.0,15.58,1.0,16.9979,0.0,NaT,NaN,NaN,NaN
11,16.665,26.0,56.0,0.0,81.0,30.0,1.0,14.76,1.0,19.0012,0.0,NaT,NaN,NaN,NaN
12,21.210,29.0,84.0,0.0,77.0,55.0,1.0,17.22,1.0,19.0012,0.0,NaT,NaN,NaN,NaN
13,22.725,47.0,94.0,0.0,72.0,47.0,1.0,18.86,2.0,19.9995,0.0,NaT,NaN,NaN,NaN
14,22.725,35.0,106.0,0.0,72.0,71.0,1.0,18.86,2.0,19.0012,0.0,NaT,NaN,NaN,NaN
15,21.970,40.0,110.0,0.0,77.0,70.0,1.0,18.04,2.0,19.9995,0.0,NaT,NaN,NaN,NaN
16,21.210,41.0,93.0,0.0,82.0,52.0,1.0,17.22,2.0,19.9995,0.0,NaT,NaN,NaN,NaN
17,21.970,15.0,67.0,0.0,82.0,52.0,1.0,18.04,2.0,19.0012,0.0,NaT,NaN,NaN,NaN
18,21.210,9.0,35.0,0.0,88.0,26.0,1.0,17.22,3.0,16.9979,0.0,NaT,NaN,NaN,NaN
19,21.210,6.0,37.0,0.0,88.0,31.0,1.0,17.22,3.0,16.9979,0.0,NaT,NaN,NaN,NaN
20,20.455,11.0,36.0,0.0,87.0,25.0,1.0,16.40,2.0,16.9979,0.0,NaT,NaN,NaN,NaN
21,20.455,3.0,34.0,0.0,87.0,31.0,1.0,16.40,2.0,12.9980,0.0,NaT,NaN,NaN,NaN
22,20.455,11.0,28.0,0.0,94.0,17.0,1.0,16.40,2.0,15.0013,0.0,NaT,NaN,NaN,NaN
23,22.725,15.0,39.0,0.0,88.0,24.0,1.0,18.86,2.0,19.9995,0.0,NaT,NaN,NaN,NaN
24,22.725,4.0,17.0,0.0,88.0,13.0,1.0,18.86,2.0,19.9995,0.0,NaT,NaN,NaN,NaN
25,21.970,1.0,17.0,0.0,94.0,16.0,1.0,18.04,2.0,16.9979,0.0,NaT,NaN,NaN,NaN
26,21.210,1.0,9.0,0.0,100.0,8.0,1.0,17.22,2.0,19.0012,0.0,NaT,NaN,NaN,NaN
27,22.725,2.0,6.0,0.0,94.0,4.0,1.0,18.86,2.0,12.9980,0.0,NaT,NaN,NaN,NaN
28,22.725,2.0,3.0,0.0,94.0,1.0,1.0,18.86,2.0,12.9980,0.0,NaT,NaN,NaN,NaN
29,21.210,0.0,2.0,0.0,77.0,2.0,1.0,17.22,3.0,19.9995,0.0,NaT,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10856,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-12-18 18:00:00,2012.0,12.0,18.0
10857,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-12-18 19:00:00,2012.0,12.0,18.0
10858,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-12-18 20:00:00,2012.0,12.0,18.0
10859,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-12-18 21:00:00,2012.0,12.0,18.0
10860,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-12-18 22:00:00,2012.0,12.0,18.0
10861,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-12-18 23:00:00,2012.0,12.0,18.0
10862,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-12-19 00:00:00,2012.0,12.0,19.0
10863,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-12-19 01:00:00,2012.0,12.0,19.0
10864,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-12-19 02:00:00,2012.0,12.0,19.0
10865,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-12-19 03:00:00,2012.0,12.0,19.0
10866,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-12-19 04:00:00,2012.0,12.0,19.0
10867,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-12-19 05:00:00,2012.0,12.0,19.0
10868,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-12-19 06:00:00,2012.0,12.0,19.0
10869,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-12-19 07:00:00,2012.0,12.0,19.0
10870,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-12-19 08:00:00,2012.0,12.0,19.0
10871,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-12-19 09:00:00,2012.0,12.0,19.0
10872,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-12-19 10:00:00,2012.0,12.0,19.0
10873,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-12-19 11:00:00,2012.0,12.0,19.0
10874,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-12-19 12:00:00,2012.0,12.0,19.0
10875,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-12-19 13:00:00,2012.0,12.0,19.0
10876,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-12-19 14:00:00,2012.0,12.0,19.0
10877,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-12-19 15:00:00,2012.0,12.0,19.0
10878,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-12-19 16:00:00,2012.0,12.0,19.0
10879,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-12-19 17:00:00,2012.0,12.0,19.0
10880,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-12-19 18:00:00,2012.0,12.0,19.0
10881,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-12-19 19:00:00,2012.0,12.0,19.0
10882,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-12-19 20:00:00,2012.0,12.0,19.0
10883,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-12-19 21:00:00,2012.0,12.0,19.0
10884,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-12-19 22:00:00,2012.0,12.0,19.0
10885,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-12-19 23:00:00,2012.0,12.0,19.0